logging:
  level:
    org.springframework.security: INFO

management:
  security:
    enabled: false # disabled the security

feign:
    hystrix:
        enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  eureka:
    enabled: true
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 7000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
