# This file is applied for all microservices

logging:
  level:
    org.springframework.security: INFO

uaa:
  server:
    port: 9999
    # Since we're using same domain name for all services, need to use context-path to avoid cookie conflicts
    # (JSESSIONID of API Gateway and UAA Server)
    context-path: /uaa
    url: http://localhost:${uaa.server.port}${uaa.server.context-path}

management:
  security:
    enabled: false # disabled the security

feign:
    hystrix:
        enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  eureka:
    enabled: true
  MaxAutoRetries: 2
  # start 2 microservice instances, try GET serveral times, then shutdown 1,
  # try GET serveral times again to see intermittent loading (due to default round-robin load balancing)
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 7000
  ConnectTimeout: 20000

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
