server:
  port: 4000

sidecar:
  port: 8000

security:
  basic:
    enabled: false
  oauth2:
    client:
      accessTokenUri: ${uaa.server.url}/oauth/token
      userAuthorizationUri: ${uaa.server.url}/oauth/authorize
      clientId: anyclient
      clientSecret: clientsecret
    resource:
      jwt:
        # just a stupid key to get rid of Missing tokenInfoUri and userInfoUri and there is no JWT verifier key
        # because we will configure token service manually
        keyValue: stupid
      id: openid

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
