spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

management:
  security:
    enabled: false # disabled the security
          
# Config server binding port
server:
  port: 8888